name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - "4.08"
          - "4.14"
          - "5.3"
        exclude:
          - os: macos-latest
            ocaml-version: "4.08"
          - os: windows-latest
            ocaml-version: "4.08"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam install . --deps-only --with-test

      - name: build project
        run: opam exec -- dune build

      - name: run test
        run: opam exec -- dune runtest

      - name: install lower bounds version
        if: matrix.os == 'ubuntu-latest'
        run: opam install . --deps-only --with-test --criteria='+removed,+count[version-lag,solution]' --solver=builtin-0install

      - name: build project with lower bounds
        if: matrix.os == 'ubuntu-latest'
        run: opam exec -- dune build

      - name: run test with lower bounds
        if: matrix.os == 'ubuntu-latest'
        run: opam exec -- dune runtest
